import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/context/AuthContext";
import ProductContextProvider from "@/context/ProductContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Furkan Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/furkan-logo.jpg" sizes="any" />
      </head>
      <body className={inter.className}>
        <AuthContextProvider>
          <ProductContextProvider>
            {children}
          </ProductContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
