import { team } from "@/helpers/data"
import Image from "next/image"
import Link from "next/link"
import { FaLinkedin, FaGithub } from "react-icons/fa";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div className="py-12">
      <div className="max-w-screen-xl mx-auto px-4 text-center md:px-8">
        <di className="max-w-xl mx-auto">
          <h3 className="text-4xl font-semibold">Meet My Team</h3>
          <p className="my-5 text-gray-600">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae, tempore! Fugiat perferendis itaque odio voluptatum quis quibusdam amet nesciunt eaque.</p>
        </di>

        <div className="mt-10">
          <div className="grid gap-24 sm:grid-cols-1 md:grid-cols-2 2xl:grid-cols-4 p-8">
            {team.map(({id, avatar, name, title, desc, linkedin, github}) => (
              <div key={id}>
                <div>
                  <Image src={avatar} alt={name} width={80} height={80} className="rounded-full mx-auto" />
                </div>
                <div className="mt-2">
                  <h4 className="font-semibold text-2xl">{name}</h4>
                  <p className="font-medium text-blue-800">{title}</p>
                  <p className="text-gray-500">{desc}</p>
                  <div className="flex justify-center items-center gap-4 mt-4">
                    <Link href={linkedin} target="_blank" className="text-2xl text-[#0270AD]">
                      <FaLinkedin />
                    </Link>
                    <Link href={github} target="_blank" className="text-2xl">
                      <FaGithub />
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default About