import Stats from '@/components/Stats'
import Testimonial from '@/components/Testimonial'
import React from 'react'

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return (
    <>
      <Stats />
      <Testimonial />
    </>
  )
}

export default Dashboard